### PR TITLE
Simplify #22 (#18 - additional carto layers)

### PR DESCRIPTION
**Pull request by jeancaffou**
I've gone through the code in more detail to understand the structure and flow. I think it can be simplified in this proposed way, let me know if it causes issues in referencing the carto layers.

### CODE REVIEW

**Comment by MaticDiba** [comment]
I tried this first, but because it renders this component every time, it also fetches capabilities every time. On the other hand it would make sense to cache this anyway. I can do that as another task. This approach also doesn't care about order in which layers were shown or hidden. Which is better.

But there is issue with setting z-index. I think styles should be used. Or maybe another secret way I'm not aware of that Vue offers ;)
```
[Vue warn]: Invalid prop: type check failed for prop "zIndex". Expected Number with value 2, got String with value "2".
```

**Comment by jeancaffou** [comment]
About z-index I didn't even check documentation, but it's an easy fix, just write `:z-index` instead of z-index (note the colon), this will make the number inside the quotes be evaluated, and thus be a Number, not a String.

About the first paragraph, I understood some of the words :))))

**Comment by jeancaffou** [comment]
So there is some loading overhead you want to avoid? Then of course using your method with watcher that sets `setVisibility()` is perfectly fine!

**Comment by MaticDiba** [comment]
Sorry about dispersed mind flow :) but yes: you got it right. I opened another ticket for next milestone :)

**Pull request closed without merging**
